version: 2
jobs:
  unit-test:
    docker:
      - image: circleci/node:11.9.0
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: 'yarn install'
      - run:
          name: unit-test
          command: 'yarn test'



workflows:
  version: 2
  build-and-publish:
    jobs:
      - unit-test
