version: 2
jobs:
  unit-test:
    docker:
      - image: circleci/node:11.9.0
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: 'yarn install'
      - run:
          name: unit-test
          command: 'yarn test'
  publish-test-env:
    docker:
      image: heroku/
    steps:
      - checkout
      - run:
          name: build-image
          command: 'docker build -t lilyevans/chore-chart:$CIRCLE_SHA1 .'
      - run:
          name: publish-image-to-docker-hub
          command: |
            docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASS
            docker push lilyevans/chore-chart:$CIRCLE_SHA1
      - run:
          name: publish-image-to-heroku
          command: |
            docker login --username=_ --password=$HEROKU_KEY registry.heroku.com
            docker tag lilyevans/chore-chart:$CIRCLE_SHA1 registry.heroku.com/chore-chart-test/web
            docker push registry.heroku.com/chore-chart-test/web



workflows:
  version: 2
  build-and-publish:
    jobs:
      - unit-test
      - publish-test-env:
          requires:
            - unit-test
