version: 2
jobs:
  unit-test:
    docker:
      - image: circleci/node:11.9.0
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: 'yarn install'
      - run:
          name: unit-test
          command: 'yarn test'
  publish-test-env:
    machine: true
    steps:
      - checkout
      - run:
          name: build-image
          command: 'docker build -t lilyevans/chore-chart:$CIRCLE_SHA1 .'
      - run:
          name: publish-image-to-docker-hub
          command: |
            docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASS
            docker push lilyevans/chore-chart:$CIRCLE_SHA1
      - run:
          name: publish-image-to-heroku
          command: |
            docker login --username=_ --password=$HEROKU_CLI_TOKEN registry.heroku.com
            docker tag lilyevans/chore-chart:$CIRCLE_SHA1 registry.heroku.com/chore-chart-test/web
            docker push registry.heroku.com/chore-chart-test/web
      - run:
          name: set-image-id
          command: 'DOCKER_IMAGE_ID=$(docker inspect registry.heroku.com/chore-chart-test/web --format={{.Id}})'
      - run:
          name: release-image-to-env
          command: |
            curl -n -X PATCH https://api.heroku.com/apps/chore-chart-test/formation \
              -d '{
              "updates": [
                {
                  "type": "web",
                  "docker_image": "'"$DOCKER_IMAGE_ID"'"
                }
              ]
            }' \
              -H "Content-Type: application/json" \
              -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
              -H "Authorization: Bearer "$HEROKU_API_KEY""

workflows:
  version: 2
  build-and-publish:
    jobs:
      - unit-test
      - publish-test-env:
          requires:
            - unit-test
